# AWS App Runner configuration for Laravel
version: 1.0

runtime: php82

source:
  commands:
    build:
      commands:
        - echo "Installing Composer dependencies"
        - composer install --optimize-autoloader --no-dev
        - echo "Caching Laravel configuration"
        - php artisan config:cache
        - php artisan route:cache
        - php artisan view:cache
        - echo "Running database migrations"
        - php artisan migrate --force
    pre_build:
      commands:
        - echo "Pre-build phase"
        - php -v
        - composer -V

run:
  runtime-version: 8.2
  commands:
    web: php artisan serve --host=0.0.0.0 --port=8000
  network:
    port: 8000
    env: PORT
  env:
    - name: APP_ENV
      value: "production"
    - name: APP_DEBUG
      value: "false"
    - name: LOG_LEVEL
      value: "error"